Update bash syntax

diff --git a/.github/workflows/push_caller_workflow.yml b/.github/workflows/push_caller_workflow.yml
--- a/.github/workflows/push_caller_workflow.yml
+++ b/.github/workflows/push_caller_workflow.yml
@@ -31,7 +31,7 @@ jobs:
         id: build-matrix
         # TODO update list variable
         run: |
-          repo_list=$(gh repo list ynput --json name,repositoryTopics | jq -r '[.[] | select(.repositoryTopics != null) | select(any(.repositoryTopics[]; .name == "${{ inputs.repo_topic }}")) | .name]')
+          repo_list=$(gh repo list ynput -L 100 --json name,repositoryTopics | jq -r '[.[] | select(.repositoryTopics != null) | select(any(.repositoryTopics[]; .name == "${{ inputs.repo_topic }}")) | .name]')
           echo "$repo_list"
           echo 'matrix=["ayon-addon-action-testing", "ayon-sample"]' >> $GITHUB_OUTPUT
 
@@ -45,11 +45,11 @@ jobs:
           repo_name: ${{ fromJson(needs.get-repos.outputs.repo_matrix) }}
 
     steps:
-      - name: Process Matrix Value
+      - name: Test repo exists
         run: |
           if ! gh repo view "ynput/${{ matrix.repo_name }}" &>/dev/null; then
-            echo "::warning::Repository ${{ matrix.repo_name }} was not found."
-            exit 0
+            echo "::error::Repository ${{ matrix.repo_name }} was not found."
+            exit 1
           fi
 
       - name: Check for running workflows
@@ -57,16 +57,17 @@ jobs:
         run: |
           for i in {1..20}; do
               running_workflows=$(gh run list --repo ${{ matrix.repo_name }} -L 100 --status in_progress --json name | jq -r 'map(.name) | join(", ")')
-              if $running_workflows; then
+              if [[ -n "$running_workflows" ]]; then
                 echo "::warning::Repo ${{ matrix.repo_name }} currently has running workflows: $running_workflows"
                 sleep 15
                 continue
+              fi
 
               break
           done
 
           running_workflows=$(gh run list --repo ${{ matrix.repo_name }} --status in_progress --json name | jq -r 'map(.name) | join(", ")')
-          if $running_workflows; then
+          if [[ -n "$running_workflows" ]]; then
             echo "::error::Repo ${{ matrix.repo_name }} currently has running workflows: $running_workflows"
             echo "::error::Repo ${{ matrix.repo_name }} has been running workflows since more then 5 minutes, please check the repo"
             exit 1
