Add changes check before committing

diff --git a/.github/workflows/push_caller_workflow.yml b/.github/workflows/push_caller_workflow.yml
--- a/.github/workflows/push_caller_workflow.yml
+++ b/.github/workflows/push_caller_workflow.yml
@@ -55,7 +55,6 @@ jobs:
           fi
 
       - name: Check for running workflows
-        id: poll-workflows
         run: |
           for i in {1..20}; do
               running_workflows=$(gh run list --repo ynput/${{ matrix.repo_name }} -L 100 --status in_progress --json name | jq -r 'map(.name) | join(", ")')
@@ -90,11 +89,35 @@ jobs:
 
           mv ${{ inputs.caller_workflow_name }}.yml ./.github/workflows/${{ inputs.caller_workflow_name }}.yml
 
-      - name: Push caller workflow
+      - name: Authenticate bot
         run: |
           git config --global user.name "${{ secrets.CI_USER }}"
           git config --global user.email "${{ secrets.CI_EMAIL }}"
 
+      - name: Check for changes
+        id: check_changes
+        run: |
+          if git diff-index --quiet HEAD --; then
+            echo "No changes to push."
+            echo "push_required=false" >> $GITHUB_OUTPUT
+            echo "::warning::No changes found, not pushing to ${{ matrix.repo_name }} at ${{ inputs.target_branch }}"
+          else
+            echo "push_required=true" >> $GITHUB_OUTPUT
+            echo "::notice::Changes pushed to ${{ matrix.repo_name }} at ${{ inputs.target_branch }}"
+          fi
+
+      - name: Push changes
+        if: steps.check_changes.outputs.push_required == 'true'
+        run: |
           git add ./.github/workflows/${{ inputs.caller_workflow_name }}.yml
-          git commit -m "[Automated] Add ${{ inputs.caller_workflow_name }} caller workflow"
-          git push origin ${{ inputs.target_branch }} || echo "No changes to push."
+          git commit -m "[Automated] Update ${{ inputs.caller_workflow_name }} caller workflow"
+          git push origin ${{ inputs.target_branch }}
+
+      # - name: Push caller workflow
+      #   run: |
+      #     git config --global user.name "${{ secrets.CI_USER }}"
+      #     git config --global user.email "${{ secrets.CI_EMAIL }}"
+
+      #     git add ./.github/workflows/${{ inputs.caller_workflow_name }}.yml
+      #     git commit -m "[Automated] Add ${{ inputs.caller_workflow_name }} caller workflow"
+      #     git push origin ${{ inputs.target_branch }} || echo "No changes to push."
