Update release verification
Update workflow names

diff --git a/.github/workflows/verify_latest_release.yml b/.github/workflows/verify_latest_release.yml
--- a/.github/workflows/verify_latest_release.yml
+++ b/.github/workflows/verify_latest_release.yml
@@ -6,6 +6,9 @@ on:
       repo:
         type: string
         required: false
+      expect_release:
+        type: boolean
+        required: false
 
     secrets:
       gh_token:
@@ -84,14 +87,20 @@ jobs:
             echo "Draft Status: ${{ steps.latest-release.outputs.draft }}"
             echo "Pre-release Status: ${{ steps.latest-release.outputs.pre_release }}"
 
-      - name: Test existing release
-        if: ${{ ! steps.latest-release.outputs.date_published }}
+      - name: Test non-existing release
+        if: steps.latest-release.outputs.date_published && !inputs.expect_release
         run: |
-          echo "::warning::No releases found for ${{ github.repository }}. Please use the Initial Release Trigger workflow.
+          echo "::error::Release already exists, but wasn't expected for ${{ inputs.repo }}. - Please use the release-trigger workflow instead"
+          exit 1
+
+      - name: Test existing release
+        if: !steps.latest-release.outputs.date_published && inputs.expect_release
+        run: |
+          echo "::error::No release found, but was expected for ${{ inputs.repo }}. - Please use the initial-release workflow instead"
           exit 1
 
       - name: Test release drafts
-        if: ${{ fromJson(steps.latest-release.outputs.draft) }}
+        if: fromJson(steps.latest-release.outputs.draft)
         run: |
           echo "::warning::Release draft already present: ${{ steps.latest-release.outputs.name }}"
           exit 0
